version: '3.9'
name: etl-service
services:

  postgres:
    build:
      context: ../
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ../core/db/init/:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d movies_database" ]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    networks:
      - services

  elastic:
    container_name: elastic
    image: elasticsearch:8.12.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    env_file:
      - ../.env
    healthcheck:
      test: curl -s http://elastic:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
      start_period: 10s
    networks:
      - services

  etl:
    build:
      context: ../
      dockerfile: etl/Dockerfile
    container_name: etl
    restart: always
    env_file:
      - ../.env
    depends_on:
      elastic:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - services

volumes:
  postgres_data:
  elastic_data:
  static:

networks:
  services: